name: math_app
description: "Matematika kursi"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.2
  auto_route: ^9.3.0+1
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.0
  intl: ^0.19.0
  firebase_storage: ^12.4.0
  flutter_widget_from_html_core: ^0.15.2
  youtube_player_flutter: ^9.1.1
  flutter_keyboard_visibility: ^6.0.0
  rive: ^0.13.20


  #UI
  flutter_svg: ^2.0.17
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_styled_toast: ^2.1.3
  chewie: ^1.8.5
  video_player: ^2.9.2
  #  pod_player: ^0.2.1
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.0.5
  get_it: ^8.0.3

  #NERWORK
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  connectivity_plus: ^6.1.2

  #DB
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



  auto_route_generator: ^9.3.1
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.7
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/png/
    - assets/translations/
    - assets/lottie/
    - assets/rive/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400