// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Xv5Zm7sykilJZliJnn8eZqTy2Jwg43s',
    appId: '1:263462803840:web:c73ad061ae341f27e84965',
    messagingSenderId: '263462803840',
    projectId: 'programmer-uz-chat-78ec2',
    authDomain: 'programmer-uz-chat-78ec2.firebaseapp.com',
    storageBucket: 'programmer-uz-chat-78ec2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbES5DeSlo-IZj8e8IXnexmp5l66_1OGs',
    appId: '1:263462803840:android:e54a81ce0cebe011e84965',
    messagingSenderId: '263462803840',
    projectId: 'programmer-uz-chat-78ec2',
    storageBucket: 'programmer-uz-chat-78ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIlKWozLLon1D7Gguqj2P7HctL69EP20M',
    appId: '1:263462803840:ios:78999466751f1cc5e84965',
    messagingSenderId: '263462803840',
    projectId: 'programmer-uz-chat-78ec2',
    storageBucket: 'programmer-uz-chat-78ec2.appspot.com',
    iosClientId: '263462803840-kkop8e5s3elneb6k4m0j511955gkte78.apps.googleusercontent.com',
    iosBundleId: 'com.example.programmeruzChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIlKWozLLon1D7Gguqj2P7HctL69EP20M',
    appId: '1:263462803840:ios:78999466751f1cc5e84965',
    messagingSenderId: '263462803840',
    projectId: 'programmer-uz-chat-78ec2',
    storageBucket: 'programmer-uz-chat-78ec2.appspot.com',
    iosClientId: '263462803840-kkop8e5s3elneb6k4m0j511955gkte78.apps.googleusercontent.com',
    iosBundleId: 'com.example.programmeruzChat',
  );
}
